### ISSUE TITLE
Updating a user avatar

### ISSUE THREAD

**Issue by skoften** [remcoov/avataaars#1]
Nice plugin, but I am missing the most important functionality: possibility to set/update the generated avatar on a user's profile. Maybe for the next release? :-)

Cheers!

**Comment by remcoov** [comment]
Hi @skoften, yes this feature is most definitely on the radar. Hope to have this implemented a.s.a.p. :)

**Comment by remcoov** [comment]
Hi @skoften, the v1.0.2 update is out with the option to render a form to let the user set their Craft CMS user photo. I suggest you check the README as well ;-)
